# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['kathara.py'],
             pathex=['../src/'],
             binaries=[],
             datas=[],
             hiddenimports=['Kathara',
                            'Kathara.cli',
                            'Kathara.cli.command',
                            'Kathara.cli.command.CheckCommand',
                            'Kathara.cli.command.ConnectCommand',
                            'Kathara.cli.command.ExecCommand',
                            'Kathara.cli.command.LcleanCommand',
                            'Kathara.cli.command.LinfoCommand',
                            'Kathara.cli.command.ListCommand',
                            'Kathara.cli.command.LrestartCommand',
                            'Kathara.cli.command.LstartCommand',
                            'Kathara.cli.command.LconfigCommand',
                            'Kathara.cli.command.SettingsCommand',
                            'Kathara.cli.command.VcleanCommand',
                            'Kathara.cli.command.VconfigCommand',
                            'Kathara.cli.command.VstartCommand',
                            'Kathara.cli.command.WipeCommand',
                            'Kathara.cli.ui',
                            'Kathara.cli.ui.setting',
                            'Kathara.cli.ui.setting.DockerOptionsHandler',
                            'Kathara.cli.ui.setting.KubernetesOptionsHandler',
                            'Kathara.manager',
                            'Kathara.manager.Kathara',
                            'Kathara.manager.docker',
                            'Kathara.manager.docker.DockerManager',
                            'Kathara.manager.kubernetes',
                            'Kathara.manager.kubernetes.KubernetesManager',
                            'Kathara.setting',
                            'Kathara.setting.addon',
                            'Kathara.setting.addon.DockerSettingsAddon',
                            'Kathara.setting.addon.KubernetesSettingsAddon'
                            ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          name='kathara',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          exclude_binaries=True,
          runtime_tmpdir=None,
          target_arch='x86',
          console=True)

col = COLLECT(exe,
              a.binaries,
              a.zipfiles,
              a.datas,
              strip=False,
              upx=True,
              upx_exclude=[],
              name='kathara'
)