# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['kathara.py'],
             pathex=['/home/lollo/git/ookathara/kathara-0.47'],
             binaries=[],
             datas=[],
             hiddenimports=['classes',
                            'classes.command',
                            'classes.command.CheckCommand',
                            'classes.command.ConnectCommand',
                            'classes.command.LcleanCommand',
                            'classes.command.LinfoCommand',
                            'classes.command.ListCommand',
                            'classes.command.LrestartCommand',
                            'classes.command.LstartCommand',
                            'classes.command.SettingsCommand',
                            'classes.command.VcleanCommand',
                            'classes.command.VersionCommand',
                            'classes.command.VstartCommand',
                            'classes.command.WipeCommand',
                            'classes.manager.docker.DockerManager',
                            'classes.manager.ManagerProxy'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='kathara',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='kathara')
