name: 'Setup Python build env'
description: 'Python 3.13 Kathará dependency, pytest and pip cache'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.13'


runs:
  using: composite
  steps:
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405   #v6.2.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: src/requirements.txt
    - shell: bash
      run: |
        python -m pip install --upgrade "setuptools<81"
        python -m pip install -r src/requirements.txt
        python -m pip install pytest