FROM ubuntu:__DISTRO__

ENV TZ=Europe/Rome
ENV RUBYOPT="-KU -E utf-8:utf-8"
ENV LANG="C.UTF-8"
ENV LC_ALL="C.UTF-8"

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG DEBIAN_FRONTEND="noninteractive"
RUN apt update && \
	apt upgrade -y && \
	apt install -y \
	apt-utils \
	bash-completion \
	build-essential \
	debhelper \
	devscripts \
	git \
	libxml2-dev \
	libffi-dev \
	lintian \
	patchelf \
	software-properties-common \
	zlib1g-dev

RUN apt install -y \
    curl \
    autoconf \
    bison \
    libssl-dev  \
    libyaml-dev  \
    libreadline6-dev  \
    libncurses5-dev \
    libgdbm6 \
    libgdbm-dev \
    libdb-dev && \
    curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash && \
    /root/.rbenv/bin/rbenv install 3.3.0 && \
    /root/.rbenv/bin/rbenv global 3.3.0

ENV PATH="/root/.rbenv/shims:/root/.rbenv/bin:$PATH"

RUN add-apt-repository ppa:deadsnakes/ppa \
	&& DEBIAN_FRONTEND=noninteractive apt install -y \
	python3.13 \
	python3.13-dev \
	python3.13-venv \
	python3-pip

RUN gem install ronn-ng
RUN mkdir /root/.gnupg && chmod 700 /root/.gnupg

COPY dput.cf /root/.dput.cf

WORKDIR /opt/kathara/scripts/Linux-Deb
